# Generated by Django 3.2.8 on 2021-12-30 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_fname', models.CharField(max_length=20)),
                ('stu_lname', models.CharField(max_length=20)),
                ('stu_id', models.CharField(max_length=10)),
                ('program', models.CharField(max_length=15)),
            ],
        ),
    ]
